import "./globals.css";
import Header from "@/component/Header";
import Navbar from '@/component/Navbar';
import Search from '@/component/Search';
export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        <Search />
        {children}
      </body>
    </html>
  );
}
